"""Rename columns

Revision ID: 28ac14ce8a69
Revises:
Create Date: 2025-07-31 14:28:45.154495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28ac14ce8a69"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voters",
        sa.Column("voter_hashed_national_id", sa.String(length=200), nullable=False),
    )
    op.drop_column("voters", "voter_hashed_id")
    op.add_column(
        "voting_processes",
        sa.Column("voter_hashed_national_id", sa.String(length=200), nullable=False),
    )
    op.drop_column("voting_processes", "voter_hashed_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voting_processes",
        sa.Column(
            "voter_hashed_id",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("voting_processes", "voter_hashed_national_id")
    op.add_column(
        "voters",
        sa.Column(
            "voter_hashed_id",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("voters", "voter_hashed_national_id")
    # ### end Alembic commands ###
