"""Add governorate to voters

Revision ID: 5dcf736b0326
Revises: 5cf9988d6340
Create Date: 2025-08-06 14:55:18.096767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcf736b0326'
down_revision: Union[str, Sequence[str], None] = '5cf9988d6340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters', sa.Column('governerate', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voters', 'governerate')
    # ### end Alembic commands ###
