"""Add candidate_voter_mappings table

Revision ID: 69b2b432139f
Revises: 5dcf736b0326
Create Date: 2025-08-12 15:28:25.606745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b2b432139f'
down_revision: Union[str, Sequence[str], None] = '5dcf736b0326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_voter_mappings',
    sa.Column('voter_hashed_national_id', sa.String(length=200), nullable=False),
    sa.Column('candidate_hashed_national_id', sa.String(length=200), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_hashed_national_id'], ['candidates.hashed_national_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_hashed_national_id'], ['voters.voter_hashed_national_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voter_hashed_national_id', 'candidate_hashed_national_id', 'election_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_voter_mappings')
    # ### end Alembic commands ###
