"""remove_create_req_status_from_candidates

Revision ID: d16926bedbff
Revises: 554339cbd5fa
Create Date: 2025-08-09 16:10:21.711783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd16926bedbff'
down_revision: Union[str, Sequence[str], None] = '554339cbd5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'create_req_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('create_req_status', postgresql.ENUM('pending', 'accepted', 'rejected', name='status'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
