"""rename_metadata_to_additional_data

Revision ID: f5672d481ab7
Revises: cf81f3ac74a8
Create Date: 2025-08-09 21:30:42.150810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5672d481ab7'
down_revision: Union[str, Sequence[str], None] = 'cf81f3ac74a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
